version: '3.4'

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - server
    environment:
      - SERVICE_SCHEME=http
      - SERVICE_HOST=localhost
      - SERVICE_PORT=4000

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
